apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wyd-homestay
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/wyd-homestay-system.git'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wyd-homestay
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
