import React, { useEffect, useState } from "react";
import { CircleHelp, MessageSquareText, Trash2 } from "lucide-react";
import { api } from "../../api.js";
import type { FaqItem, QnaPost } from "../../types.js";

export function CommunityAdminPanel({ token }: { token: string }) {
  const [faqs, setFaqs] = useState<FaqItem[]>([]); const [qnas, setQnas] = useState<QnaPost[]>([]);
  const [faq, setFaq] = useState({ category: "일반", question: "", answer: "", sortOrder: 0, published: true });
  const [answers, setAnswers] = useState<Record<string, string>>({}); const [message, setMessage] = useState("");
  const load = () => api<{ faqs: FaqItem[]; qnas: QnaPost[] }>("/api/admin/community", {}, token).then((data) => { setFaqs(data.faqs); setQnas(data.qnas); setAnswers(Object.fromEntries(data.qnas.map((q) => [q.id, q.answer || ""]))); });
  useEffect(() => { load().catch((error) => setMessage((error as Error).message)); }, [token]);
  const addFaq = async (event: React.FormEvent) => { event.preventDefault(); await api("/api/admin/faqs", { method: "POST", body: JSON.stringify(faq) }, token); setFaq({ category: "일반", question: "", answer: "", sortOrder: 0, published: true }); await load(); };
  return <section className="admin-feature-panel"><header><div><span>Community</span><h2>FAQ 및 Q&A 관리</h2><p>자주 묻는 질문을 게시하고 접수된 문의에 답변합니다.</p></div></header>{message && <p className="form-message">{message}</p>}<div className="admin-feature-grid"><form className="feature-form" onSubmit={addFaq}><div className="section-title"><CircleHelp /><h3>FAQ 등록</h3></div><div className="form-grid two"><label><span>분류</span><input value={faq.category} onChange={(e) => setFaq({ ...faq, category: e.target.value })} /></label><label><span>정렬 순서</span><input type="number" min={0} value={faq.sortOrder} onChange={(e) => setFaq({ ...faq, sortOrder: Number(e.target.value) })} /></label></div><label><span>질문</span><input required value={faq.question} onChange={(e) => setFaq({ ...faq, question: e.target.value })} /></label><label><span>답변</span><textarea required value={faq.answer} onChange={(e) => setFaq({ ...faq, answer: e.target.value })} /></label><label className="inline-check"><input type="checkbox" checked={faq.published} onChange={(e) => setFaq({ ...faq, published: e.target.checked })} />바로 공개</label><button className="primary" type="submit">FAQ 등록</button><div className="compact-list">{faqs.map((item) => <div key={item.id}><span>{item.category}</span><strong>{item.question}</strong><button title="삭제" onClick={async () => { await api(`/api/admin/faqs/${item.id}`, { method: "DELETE" }, token); await load(); }} type="button"><Trash2 size={16} /></button></div>)}</div></form><div className="feature-form"><div className="section-title"><MessageSquareText /><h3>Q&A 답변</h3></div><div className="admin-qna-list">{qnas.map((item) => <article key={item.id}><header><span>{item.category}</span><strong>{item.title}</strong><small>{item.authorName} · {item.createdAt.slice(0, 10)}</small></header><p>{item.content}</p><textarea value={answers[item.id] ?? ""} onChange={(e) => setAnswers({ ...answers, [item.id]: e.target.value })} placeholder="운영자 답변" /><div className="button-row"><button className="primary" onClick={async () => { await api(`/api/admin/qna/${item.id}/answer`, { method: "PATCH", body: JSON.stringify({ answer: answers[item.id] }) }, token); await load(); }}>답변 저장</button><button className="secondary danger" onClick={async () => { if (!confirm("문의를 삭제하시겠습니까?")) return; await api(`/api/admin/qna/${item.id}`, { method: "DELETE" }, token); await load(); }}><Trash2 size={16} /> 삭제</button></div></article>)}{!qnas.length && <p className="empty-copy">접수된 문의가 없습니다.</p>}</div></div></div></section>;
}
